default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { ENV["USER"] } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

development:
  <<: *default
  database: northstar_crm_development

test:
  <<: *default
  database: northstar_crm_test

production:
  primary:
    <<: *default
<% if ENV["DATABASE_URL"].present? %>
    url: <%= ENV["DATABASE_URL"] %>
<% else %>
    database: northstar_crm_production
    username: northstar_crm
    password: <%= ENV["NORTHSTAR_CRM_DATABASE_PASSWORD"] %>
<% end %>
